import { deepFreeze } from '../shared.js';
import { validateExercise } from './exerciseSchema.js';

const STOP = 'Stop for sharp pain, dizziness, loss of control, or concerning symptoms; choose the listed regression or end the exercise.';
const DEFAULT_RULE = { type: 'double-progression', successfulAppearancesRequired: 2, requiresUserConfirmation: true, neverIncreaseSilently: true };
const BODYWEIGHT_RULE = { type: 'quality-reps-tempo-range', requiresUserConfirmation: true, neverIncreaseSilently: true };

function prescription(sets, repTarget) { return { sets, repTarget }; }

function define({
  id, name, shortName = name, equipmentType, loadingMode, movementPattern,
  primaryMuscles, secondaryMuscles = [], unilateral = false, sets = 3, target = '8–12',
  foundation = null, lean = null, restSeconds = 75, setSeconds = 40,
  cues, setup, mistakes = [], regression, substitutions = []
}) {
  const bodyweight = loadingMode.includes('bodyweight') || loadingMode === 'pull-up-progression';
  return {
    id, version: 1, name, shortName, equipmentType, loadingMode, movementPattern,
    primaryMuscles, secondaryMuscles, unilateral,
    defaultPrescription: prescription(sets, target),
    foundationPrescription: foundation || prescription(sets, target),
    leanAthleticPrescription: lean || prescription(sets, target),
    calibrationRule: { responses: ['too-light', 'appropriate', 'too-heavy'], weeks: [1, 2], keyedBy: 'exerciseId' },
    progressionRule: bodyweight ? BODYWEIGHT_RULE : DEFAULT_RULE,
    regressionRule: { exerciseId: regression || substitutions[0] || id, preserveHistoryIdentity: true },
    restSeconds, formCues: cues, setupSteps: setup, commonMistakes: mistakes,
    safetyNotes: ['Use a controlled range and a stable home setup.', STOP], painWarnings: [STOP],
    substitutions, videoSearchTerm: `${name} safe form`, writtenGuidanceSearchTerm: `${name} exercise guide`,
    estimatedSetDurationSeconds: setSeconds
  };
}

const records = [
  define({id:'barbell-romanian-deadlift',name:'Barbell Romanian deadlift',equipmentType:'barbell',loadingMode:'barbell-symmetric',movementPattern:'hinge',primaryMuscles:['hamstrings','glutes'],secondaryMuscles:['back','grip'],cues:['Push the hips back with soft knees.','Keep the bar close and spine controlled.'],setup:['Stand over a floor-loaded bar and brace before lifting.'],mistakes:['Do not chase floor depth by rounding.'],regression:'dumbbell-romanian-deadlift',substitutions:['dumbbell-romanian-deadlift','bodyweight-hip-hinge']}),
  define({id:'conventional-barbell-deadlift',name:'Conventional barbell deadlift',shortName:'Barbell deadlift',equipmentType:'barbell',loadingMode:'barbell-symmetric',movementPattern:'hinge',primaryMuscles:['glutes','hamstrings','quadriceps'],secondaryMuscles:['back','grip'],sets:3,target:'5–8',restSeconds:120,cues:['Brace before the bar leaves the floor.','Push the floor away and keep the bar close.'],setup:['Load the bar symmetrically on a clear, level floor.'],mistakes:['Do not jerk the bar or round under load.'],regression:'barbell-romanian-deadlift',substitutions:['barbell-romanian-deadlift','dumbbell-romanian-deadlift']}),
  define({id:'barbell-floor-press',name:'Barbell floor press',equipmentType:'barbell',loadingMode:'barbell-symmetric',movementPattern:'horizontal-push',primaryMuscles:['chest','triceps'],secondaryMuscles:['front-deltoids'],cues:['Keep wrists stacked over elbows.','Pause the upper arms gently on the floor.'],setup:['Lie on a clear floor and position the bar so it can be safely rolled into place.'],mistakes:['Do not bounce elbows or use an unsafe grip.'],regression:'dumbbell-floor-press',substitutions:['dumbbell-floor-press','push-up','incline-push-up']}),
  define({id:'barbell-bent-over-row',name:'Barbell bent-over row',equipmentType:'barbell',loadingMode:'barbell-symmetric',movementPattern:'horizontal-pull',primaryMuscles:['upper-back','lats'],secondaryMuscles:['biceps','rear-deltoids'],cues:['Hold a stable hip hinge.','Pull toward the lower ribs without shrugging.'],setup:['Hinge over a floor-loaded bar with room around you.'],mistakes:['Do not turn each rep into a torso swing.'],regression:'one-arm-dumbbell-row',substitutions:['one-arm-dumbbell-row']}),
  define({id:'barbell-glute-bridge',name:'Barbell glute bridge',equipmentType:'barbell',loadingMode:'barbell-symmetric',movementPattern:'hip-extension',primaryMuscles:['glutes'],secondaryMuscles:['hamstrings'],target:'10–15',cues:['Drive through the full foot.','Finish with glutes, not lower-back arching.'],setup:['Pad the bar across the hips and plant both feet.'],mistakes:['Do not overextend the lower back.'],regression:'bodyweight-glute-bridge',substitutions:['bodyweight-glute-bridge']}),
  define({id:'barbell-curl',name:'Barbell curl',equipmentType:'barbell',loadingMode:'barbell-symmetric',movementPattern:'elbow-flexion',primaryMuscles:['biceps'],secondaryMuscles:['forearms'],target:'8–12',cues:['Keep elbows near the ribs.','Lift without swinging the torso.'],setup:['Stand tall holding the symmetrically loaded bar.'],mistakes:['Do not lean back to finish reps.'],regression:'dumbbell-curl',substitutions:['dumbbell-curl','dumbbell-hammer-curl']}),
  define({id:'goblet-squat',name:'Goblet squat',equipmentType:'dumbbell',loadingMode:'single-dumbbell',movementPattern:'squat',primaryMuscles:['quadriceps','glutes'],secondaryMuscles:['core'],cues:['Sit between the hips with the full foot planted.','Let knees track with toes.'],setup:['Hold one dumbbell securely at chest height.'],mistakes:['Do not let knees collapse inward.'],regression:'bodyweight-squat',substitutions:['bodyweight-squat','static-split-squat','dumbbell-bulgarian-split-squat']}),
  define({id:'dumbbell-floor-press',name:'Dumbbell floor press',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'horizontal-push',primaryMuscles:['chest','triceps'],secondaryMuscles:['front-deltoids'],cues:['Keep wrists over elbows.','Lower under control until upper arms meet the floor.'],setup:['Sit with matched dumbbells, roll safely to the floor, and plant the feet.'],regression:'incline-push-up',substitutions:['push-up','incline-push-up']}),
  define({id:'dumbbell-squeeze-floor-press',name:'Dumbbell squeeze floor press',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'horizontal-push',primaryMuscles:['chest','triceps'],secondaryMuscles:['front-deltoids'],cues:['Press the dumbbells together throughout.','Keep wrists neutral and lower slowly.'],setup:['Lie on the floor holding matched dumbbells together over the chest.'],regression:'dumbbell-floor-press',substitutions:['dumbbell-floor-press','push-up']}),
  define({id:'one-arm-dumbbell-row',name:'One-arm dumbbell row',equipmentType:'dumbbell',loadingMode:'single-dumbbell',movementPattern:'horizontal-pull',primaryMuscles:['lats','upper-back'],secondaryMuscles:['biceps'],unilateral:true,target:'8–12 each side',setSeconds:70,cues:['Brace the free hand on your thigh.','Pull the elbow toward the hip without twisting.'],setup:['Use a staggered stance and a stable thigh brace; no bench is required.'],regression:'barbell-bent-over-row',substitutions:['barbell-bent-over-row']}),
  define({id:'standing-dumbbell-overhead-press',name:'Standing dumbbell overhead press',shortName:'Dumbbell overhead press',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'vertical-push',primaryMuscles:['shoulders','triceps'],secondaryMuscles:['core'],cues:['Brace the ribs over the pelvis.','Press overhead without leaning back.'],setup:['Stand with matched dumbbells at shoulder height and clear overhead space.'],regression:'single-arm-dumbbell-overhead-press',substitutions:['single-arm-dumbbell-overhead-press']}),
  define({id:'dumbbell-reverse-lunge',name:'Dumbbell reverse lunge',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'lunge',primaryMuscles:['quadriceps','glutes'],secondaryMuscles:['hamstrings','core'],unilateral:true,target:'8–12 each side',setSeconds:75,cues:['Step back far enough to keep the front foot planted.','Drive through the full front foot.'],setup:['Stand tall with matched dumbbells steady at your sides.'],regression:'bodyweight-reverse-lunge',substitutions:['bodyweight-reverse-lunge','goblet-squat']}),
  define({id:'dumbbell-bulgarian-split-squat',name:'Dumbbell Bulgarian split squat',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'lunge',primaryMuscles:['quadriceps','glutes'],secondaryMuscles:['hamstrings','core'],unilateral:true,target:'8–12 each side',setSeconds:75,cues:['Keep most pressure through the front foot.','Lower under control without twisting.'],setup:['Place the rear foot on a low, stable household support; use bodyweight if balance is uncertain.'],regression:'bodyweight-bulgarian-split-squat',substitutions:['bodyweight-bulgarian-split-squat','bodyweight-reverse-lunge']}),
  define({id:'dumbbell-lateral-raise',name:'Dumbbell lateral raise',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'shoulder-abduction',primaryMuscles:['side-deltoids'],secondaryMuscles:[],sets:2,target:'12–20',restSeconds:60,cues:['Raise with soft elbows.','Stop near shoulder height without shrugging.'],setup:['Stand tall with light matched dumbbells.'],regression:'single-arm-dumbbell-lateral-raise',substitutions:['single-arm-dumbbell-lateral-raise']}),
  define({id:'single-arm-dumbbell-lateral-raise',name:'Single-arm dumbbell lateral raise',equipmentType:'dumbbell',loadingMode:'single-dumbbell',movementPattern:'shoulder-abduction',primaryMuscles:['side-deltoids'],unilateral:true,sets:2,target:'12–20 each side',setSeconds:65,restSeconds:45,cues:['Keep the torso still.','Lead gently with the elbow.'],setup:['Use the free hand for light balance support.'],regression:'dumbbell-lateral-raise',substitutions:['dumbbell-lateral-raise']}),
  define({id:'dumbbell-pullover',name:'Dumbbell pullover',equipmentType:'dumbbell',loadingMode:'single-dumbbell',movementPattern:'vertical-pull',primaryMuscles:['lats','chest'],secondaryMuscles:['triceps'],target:'8–12',cues:['Keep ribs controlled.','Use only a comfortable shoulder range.'],setup:['Lie securely on the floor holding one dumbbell above the chest.'],mistakes:['Do not chase excessive depth.'],regression:'one-arm-dumbbell-row',substitutions:['one-arm-dumbbell-row']}),
  define({id:'dumbbell-curl',name:'Dumbbell curl',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'elbow-flexion',primaryMuscles:['biceps'],secondaryMuscles:['forearms'],sets:2,target:'8–15',restSeconds:60,cues:['Keep elbows quiet.','Control both lowering phases.'],setup:['Stand tall with matched dumbbells at your sides.'],regression:'dumbbell-hammer-curl',substitutions:['dumbbell-hammer-curl','barbell-curl']}),
  define({id:'dumbbell-hammer-curl',name:'Dumbbell hammer curl',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'elbow-flexion',primaryMuscles:['biceps','brachialis'],secondaryMuscles:['forearms'],sets:2,target:'8–15',restSeconds:60,cues:['Keep palms facing inward.','Avoid swinging.'],setup:['Stand tall with matched dumbbells at your sides.'],regression:'dumbbell-curl',substitutions:['dumbbell-curl']}),
  define({id:'overhead-dumbbell-triceps-extension',name:'Overhead dumbbell triceps extension',equipmentType:'dumbbell',loadingMode:'single-dumbbell',movementPattern:'elbow-extension',primaryMuscles:['triceps'],sets:2,target:'10–15',restSeconds:60,cues:['Keep upper arms mostly vertical.','Control the bottom position without arching.'],setup:['Hold one dumbbell securely overhead with both hands.'],regression:'lying-dumbbell-triceps-extension',substitutions:['lying-dumbbell-triceps-extension','close-grip-push-up']}),
  define({id:'lying-dumbbell-triceps-extension',name:'Lying dumbbell triceps extension',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'elbow-extension',primaryMuscles:['triceps'],sets:2,target:'10–15',restSeconds:60,cues:['Keep upper arms steady.','Lower slowly beside the head.'],setup:['Lie on a clear floor holding matched dumbbells above the shoulders.'],regression:'overhead-dumbbell-triceps-extension',substitutions:['overhead-dumbbell-triceps-extension','close-grip-push-up']}),
  define({id:'standing-dumbbell-calf-raise',name:'Standing dumbbell calf raise',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'calf-raise',primaryMuscles:['calves'],sets:3,target:'12–20',restSeconds:60,cues:['Rise through the big toe and pause.','Lower under control.'],setup:['Stand on level ground with matched dumbbells and nearby balance support.'],regression:'bodyweight-calf-raise',substitutions:['bodyweight-calf-raise']}),
  define({id:'push-up',name:'Push-up',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'horizontal-push',primaryMuscles:['chest','triceps'],secondaryMuscles:['front-deltoids','core'],sets:2,target:'controlled reps before failure',restSeconds:75,cues:['Keep ribs and hips aligned.','Lower with elbows at a comfortable angle.'],setup:['Place hands on a non-slip floor slightly wider than shoulders.'],regression:'incline-push-up',substitutions:['incline-push-up','dumbbell-floor-press','paused-push-up']}),
  define({id:'incline-push-up',name:'Incline push-up',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'horizontal-push',primaryMuscles:['chest','triceps'],sets:2,target:'controlled reps before failure',cues:['Use a stable surface.','Keep the body in one line.'],setup:['Place hands on a stable, non-moving surface.'],regression:'incline-push-up',substitutions:['push-up']}),
  define({id:'paused-push-up',name:'Paused push-up',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'horizontal-push',primaryMuscles:['chest','triceps'],sets:2,target:'controlled reps with 1-sec pause',cues:['Stay braced during the pause.','Press without losing alignment.'],setup:['Set up as for a standard push-up.'],regression:'push-up',substitutions:['push-up','incline-push-up']}),
  define({id:'close-grip-push-up',name:'Close-grip push-up',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'elbow-extension',primaryMuscles:['triceps','chest'],sets:2,target:'controlled reps before failure',cues:['Keep hands comfortably close.','Keep elbows tracking back.'],setup:['Use the floor or a stable incline.'],regression:'incline-push-up',substitutions:['overhead-dumbbell-triceps-extension']}),
  define({id:'bodyweight-reverse-lunge',name:'Bodyweight reverse lunge',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'lunge',primaryMuscles:['quadriceps','glutes'],unilateral:true,target:'8–12 each side',setSeconds:70,cues:['Step back under control.','Drive through the front foot.'],setup:['Stand near stable balance support if needed.'],regression:'static-split-squat',substitutions:['static-split-squat','goblet-squat']}),
  define({id:'bodyweight-bulgarian-split-squat',name:'Bodyweight Bulgarian split squat',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'lunge',primaryMuscles:['quadriceps','glutes'],unilateral:true,target:'8–12 each side',setSeconds:70,cues:['Keep the front foot planted.','Use balance support as needed.'],setup:['Place the rear foot on a low, stable support.'],regression:'bodyweight-reverse-lunge',substitutions:['bodyweight-reverse-lunge']}),
  define({id:'front-plank',name:'Front plank',equipmentType:'bodyweight',loadingMode:'timed-bodyweight',movementPattern:'core-bracing',primaryMuscles:['core'],sets:2,target:'20–45 seconds',restSeconds:45,setSeconds:35,cues:['Keep ribs over pelvis.','Breathe without losing position.'],setup:['Place forearms on a non-slip floor.'],regression:'dead-bug',substitutions:['dead-bug']}),
  define({id:'side-plank',name:'Side plank',equipmentType:'bodyweight',loadingMode:'timed-bodyweight',movementPattern:'lateral-core',primaryMuscles:['obliques'],secondaryMuscles:['shoulders'],sets:2,target:'20–40 seconds each side',restSeconds:45,setSeconds:75,cues:['Keep hips stacked.','Press the floor away.'],setup:['Lie on one side with elbow under shoulder.'],regression:'dead-bug',substitutions:['reverse-crunch','dead-bug']}),
  define({id:'dead-bug',name:'Dead bug',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'core-bracing',primaryMuscles:['core'],unilateral:true,sets:2,target:'8–12 each side',restSeconds:45,setSeconds:65,cues:['Keep the lower back gently supported.','Move slowly without rib flare.'],setup:['Lie on the floor with hips and knees bent.'],regression:'front-plank',substitutions:['front-plank']}),
  define({id:'reverse-crunch',name:'Reverse crunch',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'trunk-flexion',primaryMuscles:['abdominals'],sets:2,target:'10–15',restSeconds:45,cues:['Curl the pelvis without swinging.','Lower slowly.'],setup:['Lie on a clear floor with knees bent.'],regression:'dead-bug',substitutions:['side-plank','dead-bug']}),
  define({id:'bodyweight-glute-bridge',name:'Bodyweight glute bridge',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'hip-extension',primaryMuscles:['glutes'],sets:3,target:'10–15',cues:['Drive through the full foot.','Finish with the glutes.'],setup:['Lie on the floor with knees bent and feet planted.'],regression:'bodyweight-glute-bridge',substitutions:['barbell-glute-bridge']}),
  define({id:'pull-up-progression',name:'Pull-up progression',equipmentType:'pull-up-bar',loadingMode:'pull-up-progression',movementPattern:'vertical-pull',primaryMuscles:['lats','biceps'],secondaryMuscles:['grip','shoulder-stabilisers'],sets:3,target:'rung-specific controlled work',cues:['Use the selected rung with control.','Never kip or use an unconfirmed bar.'],setup:['Install and safety-confirm the bar, then resolve the current rung before starting.'],regression:'scapular-pull-up',substitutions:['dumbbell-pullover','scapular-pull-up']}),
  define({id:'dead-hang',name:'Dead hang',equipmentType:'pull-up-bar',loadingMode:'pull-up-progression',movementPattern:'vertical-pull',primaryMuscles:['grip','shoulder-stabilisers'],sets:3,target:'15–25 seconds',cues:['Use a secure grip.','Keep the shoulders controlled.'],setup:['Safety-confirm the bar and use a stable step.'],regression:'dead-hang',substitutions:['dumbbell-pullover']}),
  define({id:'scapular-pull-up',name:'Scapular pull-up',equipmentType:'pull-up-bar',loadingMode:'pull-up-progression',movementPattern:'vertical-pull',primaryMuscles:['lats','shoulder-stabilisers'],sets:3,target:'5 controlled reps',cues:['Keep elbows straight.','Move only through the shoulder blades.'],setup:['Safety-confirm the bar and begin from a controlled hang.'],regression:'dead-hang',substitutions:['dead-hang','dumbbell-pullover']}),
  define({id:'controlled-negative-pull-up',name:'Controlled negative pull-up',equipmentType:'pull-up-bar',loadingMode:'pull-up-progression',movementPattern:'vertical-pull',primaryMuscles:['lats','biceps'],sets:3,target:'3 reps with 3–5 sec lowering',cues:['Step safely to the top.','Lower without dropping.'],setup:['Safety-confirm the bar and use a stable step.'],regression:'scapular-pull-up',substitutions:['scapular-pull-up','dumbbell-pullover']}),
  define({id:'assisted-pull-up',name:'Assisted pull-up',equipmentType:'pull-up-bar',loadingMode:'bodyweight-assisted',movementPattern:'vertical-pull',primaryMuscles:['lats','biceps'],sets:3,target:'5–8 controlled reps',cues:['Use only stable foot assistance.','Lead the chest without swinging.'],setup:['Safety-confirm the bar and arrange stable assistance.'],regression:'controlled-negative-pull-up',substitutions:['controlled-negative-pull-up','dumbbell-pullover']}),
  define({id:'strict-pull-up',name:'Strict pull-up',equipmentType:'pull-up-bar',loadingMode:'pull-up-progression',movementPattern:'vertical-pull',primaryMuscles:['lats','biceps'],sets:3,target:'3–6 controlled reps',cues:['Start from controlled shoulders.','Pull without kipping.'],setup:['Safety-confirm the bar and use a secure grip.'],regression:'assisted-pull-up',substitutions:['assisted-pull-up','dumbbell-pullover']}),
  define({id:'bodyweight-squat',name:'Bodyweight squat',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'squat',primaryMuscles:['quadriceps','glutes'],cues:['Keep the full foot down.','Track knees with toes.'],setup:['Stand with clear space and use support if needed.'],regression:'bodyweight-squat',substitutions:['goblet-squat']}),
  define({id:'static-split-squat',name:'Static split squat',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'lunge',primaryMuscles:['quadriceps','glutes'],unilateral:true,target:'8–12 each side',cues:['Keep both feet planted.','Lower straight down under control.'],setup:['Take a comfortable split stance near balance support.'],regression:'bodyweight-squat',substitutions:['bodyweight-reverse-lunge']}),
  define({id:'dumbbell-romanian-deadlift',name:'Dumbbell Romanian deadlift',equipmentType:'dumbbells',loadingMode:'two-dumbbells-matched',movementPattern:'hinge',primaryMuscles:['hamstrings','glutes'],cues:['Push hips back.','Keep dumbbells close to the legs.'],setup:['Stand tall holding matched dumbbells.'],regression:'bodyweight-hip-hinge',substitutions:['bodyweight-hip-hinge','barbell-romanian-deadlift']}),
  define({id:'bodyweight-hip-hinge',name:'Bodyweight hip hinge',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'hinge',primaryMuscles:['hamstrings','glutes'],cues:['Push hips back toward a wall.','Keep the spine controlled.'],setup:['Stand with feet hip-width and clear space behind.'],regression:'bodyweight-hip-hinge',substitutions:['dumbbell-romanian-deadlift']}),
  define({id:'single-arm-dumbbell-overhead-press',name:'Single-arm dumbbell overhead press',equipmentType:'dumbbell',loadingMode:'single-dumbbell',movementPattern:'vertical-push',primaryMuscles:['shoulders','triceps'],unilateral:true,target:'8–12 each side',cues:['Brace before each press.','Avoid leaning sideways.'],setup:['Stand with one dumbbell at shoulder height.'],regression:'standing-dumbbell-overhead-press',substitutions:['standing-dumbbell-overhead-press']}),
  define({id:'bodyweight-calf-raise',name:'Bodyweight calf raise',equipmentType:'bodyweight',loadingMode:'bodyweight',movementPattern:'calf-raise',primaryMuscles:['calves'],target:'12–20',cues:['Rise through the big toe.','Pause at the top.'],setup:['Stand on level ground near balance support.'],regression:'bodyweight-calf-raise',substitutions:['standing-dumbbell-calf-raise']})
];

records.forEach(validateExercise);
const byId = Object.fromEntries(records.map(record => [record.id, deepFreeze(record)]));
if (Object.keys(byId).length !== records.length) throw new Error('Exercise IDs must be unique.');

export const exerciseCatalog = deepFreeze({ id: 'proof-fitness-exercise-catalog', version: 1, exercises: byId });
export const exercises = exerciseCatalog.exercises;
export function getExercise(id) {
  const exercise = exercises[id];
  if (!exercise) throw new Error(`Unknown exercise: ${id}`);
  return exercise;
}
